Repository Fretadao/f_service, pull requests merged in 2020-10, with the labels that each got.

#12 Add support to multiple values on on_success and on_failure hooks
  CHANGELOG.md
  lib/f_service/result/base.rb
  spec/f_service/result/failure_spec.rb
  spec/f_service/result/success_spec.rb
Labels: hacktoberfest

#15 Improve on_success/on_failure documentation
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#16 Add to proc support
  README.md
  lib/f_service/base.rb
  spec/f_service/base_spec.rb
Labels: hacktoberfest, hacktoberfest-accepted

#18 Add data prop to FService::Base#Check
  CHANGELOG.md
  lib/f_service/base.rb
  spec/f_service/base_spec.rb
Labels: hacktoberfest-accepted
